TechStore.Web/Controllers/LaptopController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechStore.Core.Contracts;
using System.Security.Claims;
using TechStore.Core.Exceptions;
using TechStore.Core.Extensions;
using TechStore.Core.Models.Laptop;
using static TechStore.Infrastructure.Constants.DataConstant.RoleConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ClientConstants;
using static TechStore.Infrastructure.Constants.DataConstant.GlobalConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ProductConstants;

namespace TechStore.Web.Controllers
{
    [Authorize]
    public class LaptopController : Controller
    {
        private readonly ILaptopService laptopService;
        private readonly IClientService clientService;
        private readonly IUserService userService;

		public LaptopController(ILaptopService laptopService, IClientService clientService, IUserService userService)
        {
            this.laptopService = laptopService;
            this.clientService = clientService;
            this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AllLaptopsQueryModel query)
        {
	        var result = await this.laptopService.GetAllLaptopsAsync(
		        query.Cpu,
		        query.Ram,
		        query.SsdCapacity,
		        query.VideoCard,
		        query.Keyword,
		        query.Sorting,
                query.CurrentPage);

            query.TotalProductsCount = result.TotalLaptopsCount;

            query.Cpus = await this.laptopService.GetAllCpusNamesAsync();
            query.Rams = await this.laptopService.GetAllRamsValuesAsync();
            query.SsdCapacities = await this.laptopService.GetAllSsdCapacitiesValuesAsync();
            query.VideoCards = await this.laptopService.GetAllVideoCardsNamesAsync();

            query.Laptops = result.Laptops;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            try
            {
                var laptop = await this.laptopService.GetLaptopByIdAsLaptopDetailsExportViewModelAsync(id);

                if (information.ToLower() != laptop.GetInformation().ToLower())
                {
                    return NotFound();
                }
                
                return View(laptop);
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }
        
        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var laptop = await this.laptopService.GetLaptopByIdAsLaptopDetailsExportViewModelAsync(id);

                if (this.User.IsInRole(BestUser)
                    && (laptop.Seller is null || this.User.Id() != laptop.Seller.UserId))
                {
                    return Unauthorized();
                }

                await this.laptopService.DeleteLaptopAsync(id);

                TempData[TempDataMessage] = ProductSuccessfullyDeleted;

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add()
        {
            if (this.User.IsInRole(BestUser))
            {
                var userId = this.User.Id();

                try
                {
                    var numberOfActiveSales = await this.clientService.GetNumberOfActiveSales(userId);

                    if (numberOfActiveSales == MaxNumberOfAllowedSales)
                    {
                        ViewData["Title"] = "Add a Laptop";

                        return View(AddNotAllowedViewName);
                    }
                }
                catch (TechStoreException)
                {
	                return View(ErrorCommonViewName);
                }
            }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add(LaptopImportViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                string? userId = null;

                if (this.User.IsInRole(BestUser))
                {
                    userId = this.User.Id();
                }

                int id = await this.laptopService.AddLaptopAsync(model, userId);

                TempData[TempDataMessage] = ProductSuccessfullyAdded;

                return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
            }
            catch (TechStoreException)
            {
	            return View(ErrorCommonViewName);
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var laptop = await this.laptopService.GetLaptopByIdAsLaptopEditViewModelAsync(id);

                if (this.User.IsInRole(BestUser)
                    && (laptop.Seller is null || this.User.Id() != laptop.Seller.UserId))
                {
                    return Unauthorized();
                }

                return View(laptop);
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(LaptopEditViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var laptop = await this.laptopService.GetLaptopByIdAsLaptopEditViewModelAsync(model.Id);

                if (this.User.IsInRole(BestUser)
                    && (laptop.Seller is null || this.User.Id() != laptop.Seller.UserId))
                {
                    return Unauthorized();
                }

                int id = await this.laptopService.EditLaptopAsync(model);

                TempData[TempDataMessage] = ProductSuccessfullyEdited;

                return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = BestUser)]
        public async Task<IActionResult> Mine()
        {
            var userId = this.User.Id();

            try
            {
                var userLaptops = await this.laptopService.GetUserLaptopsAsync(userId);
                return View(userLaptops);
            }
            catch (TechStoreException)
            {
	            return View(ErrorCommonViewName);
            }
        }

        [HttpGet]
        public async Task<IActionResult> Buy(int id)
        {
	        if (this.User.IsInRole(Administrator))
	        {
				return Unauthorized();
			}

	        try
	        {
		        var userId = this.User.Id();
		        if (this.User.IsInRole(BestUser))
		        {
			        var laptopSeller = (await this.laptopService.GetLaptopByIdAsLaptopEditViewModelAsync(id)).Seller;
			        if (laptopSeller is not null && laptopSeller.UserId == userId)
			        {
				        return Unauthorized();
			        }
		        }


				ViewData["Title"] = "Buy a Laptop";
		        
				await this.laptopService.MarkLaptopAsBoughtAsync(id);
		        
		        var client = await this.clientService.BuyProduct(userId);

				var isNowPromotedToBestUser = await this.userService.ShouldBePromotedToBestUser(client);

				if (isNowPromotedToBestUser)
				{
					return View(PromoteToBestUserViewName);
				}

				return View(PurchaseMadeViewName);
			}
	        catch (ArgumentException)
	        {
				return NotFound();
			}
        }
	}
}

TechStore.Web/Controllers/MouseController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechStore.Core.Contracts;
using TechStore.Core.Exceptions;
using TechStore.Core.Extensions;
using TechStore.Core.Models.Mice;
using static TechStore.Infrastructure.Constants.DataConstant.RoleConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ProductConstants;
using static TechStore.Infrastructure.Constants.DataConstant.GlobalConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ClientConstants;

namespace TechStore.Web.Controllers
{
	public class MouseController : Controller
	{
		private readonly IMouseService mouseService;
		private readonly IClientService clientService;
		private readonly IUserService userService;

		public MouseController(IMouseService mouseService, IClientService clientService, IUserService userService)
		{
			this.mouseService = mouseService;
			this.clientService = clientService;
			this.userService = userService;
		}

		[HttpGet]
		public async Task<IActionResult> Index([FromQuery] AllMiceQueryModel query)
		{
			var result = await this.mouseService.GetAllMiceAsync(
				query.Type,
				query.Sensitivity,
				query.Wireless,
				query.Keyword,
				query.Sorting,
				query.CurrentPage);

			query.TotalProductsCount = result.TotalMiceCount;

			query.Types = await this.mouseService.GetAllMiceTypesAsync();
			query.Sensitivities = await this.mouseService.GetAllMiceSensitivitiesAsync();

			query.Mice = result.Mice;

			return View(query);
		}

		[HttpGet]
		public async Task<IActionResult> Details(int id, string information)
		{
			try
			{
				var mouse = await this.mouseService.GetMouseByIdAsMouseDetailsExportViewModelAsync(id);

				if (information.ToLower() != mouse.GetInformation().ToLower())
				{
					return NotFound();
				}

				return View(mouse);

			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				var mouse = await this.mouseService.GetMouseByIdAsMouseDetailsExportViewModelAsync(id);

				if (this.User.IsInRole(BestUser)
				    && (mouse.Seller is null || this.User.Id() != mouse.Seller.UserId))
				{
					return Unauthorized();
				}

				await this.mouseService.DeleteMouseAsync(id);

				TempData[TempDataMessage] = ProductSuccessfullyDeleted;

				return RedirectToAction(nameof(Index));

			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Add()
		{
			if (this.User.IsInRole(BestUser))
			{
				var userId = this.User.Id();

				try
				{
					var numberOfActiveSales = await this.clientService.GetNumberOfActiveSales(userId);

					if (numberOfActiveSales == MaxNumberOfAllowedSales)
					{
						ViewData["Title"] = "Add a Mouse";

						return View(AddNotAllowedViewName);
					}
				}
				catch (TechStoreException)
				{
					return View(ErrorCommonViewName);
				}
			}

			var model = new MouseImportViewModel
			{
				Sensitivities = await this.mouseService.GetAllMiceSensitivitiesAsync()
			};

			return View(model);
		}

		[HttpPost]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Add(MouseImportViewModel model, bool? rbIsWireless, string? rbSensitivity)
		{
			if (rbIsWireless is null && rbSensitivity is null)
			{
				this.ModelState.AddModelError("IsWireless", ErrorMessageForUnselectedOption);

				this.ModelState.AddModelError("Sensitivity", ErrorMessageForUnselectedOption);
			}
			else if (rbIsWireless is null)
			{
				this.ModelState.AddModelError("IsWireless", ErrorMessageForUnselectedOption);

				model.Sensitivity = rbSensitivity;
			}
			else if (rbSensitivity is null)
			{
				this.ModelState.AddModelError("Sensitivity", ErrorMessageForUnselectedOption);

				model.IsWireless = rbIsWireless;
			}
			else
			{
				model.IsWireless = rbIsWireless;

				model.Sensitivity = rbSensitivity;
			}

			if (!this.ModelState.IsValid)
			{
				model.Sensitivities = await this.mouseService.GetAllMiceSensitivitiesAsync();

				return View(model);
			}

			string? userId = null;

			if (this.User.IsInRole(BestUser))
			{
				userId = this.User.Id();
			}

			try
			{
				int id = await this.mouseService.AddMouseAsync(model, userId);

				TempData[TempDataMessage] = ProductSuccessfullyAdded;

				return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
			}
			catch (TechStoreException)
			{
				return View(ErrorCommonViewName);
			}
			catch (ArgumentException)
			{
				return View(ErrorCommonViewName);
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Edit(int id)
		{
			try
			{
				var mouse = await this.mouseService.GetMouseByIdAsMouseEditViewModelAsync(id);

				if (this.User.IsInRole(BestUser)
				    && (mouse.Seller is null || this.User.Id() != mouse.Seller.UserId))
				{
					return Unauthorized();
				}

				mouse.Sensitivities = await this.mouseService.GetAllMiceSensitivitiesAsync();

				return View(mouse);
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpPost]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Edit(MouseEditViewModel model)
		{
			if (!this.ModelState.IsValid)
			{
				return View(model);
			}

			try
			{
				var mouse = await this.mouseService.GetMouseByIdAsMouseEditViewModelAsync(model.Id);

				if (this.User.IsInRole(BestUser)
				    && (mouse.Seller is null || this.User.Id() != mouse.Seller.UserId))
				{
					return Unauthorized();
				}

				int id = await this.mouseService.EditMouseAsync(model);

				TempData[TempDataMessage] = ProductSuccessfullyEdited;

				return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = BestUser)]
		public async Task<IActionResult> Mine()
		{
			var userId = this.User.Id();

			try
			{
				var userMice = await this.mouseService.GetUserMiceAsync(userId);

				return View(userMice);
			}
			catch (TechStoreException)
			{
				return View(ErrorCommonViewName);
			}
		}

		[HttpGet]
		public async Task<IActionResult> Buy(int id)
		{
			if (this.User.IsInRole(Administrator))
			{
				return Unauthorized();
			}

			try
			{
				var userId = this.User.Id();

				if (this.User.IsInRole(BestUser))
				{
					var mouseSeller = (await this.mouseService.GetMouseByIdAsMouseEditViewModelAsync(id)).Seller;

					if (mouseSeller is not null && mouseSeller.UserId == userId)
					{
						return Unauthorized();
					}
				}

				ViewData["Title"] = "Buy a Mouse";

				await this.mouseService.MarkMouseAsBoughtAsync(id);

				var client = await this.clientService.BuyProduct(userId);

				var isNowPromotedToBestUser = await this.userService.ShouldBePromotedToBestUser(client);

				if (isNowPromotedToBestUser)
				{
					return View(PromoteToBestUserViewName);
				}

				return View(PurchaseMadeViewName);

			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}
	}
}

TechStore.Web/Areas/Administration/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TechStore.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-danger border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-warning fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Admin Page</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!-- Потребителски секции -->
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Laptop" asp-action="Index">Laptops</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Television" asp-action="Index">Televisions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Mouse" asp-action="Index">Mice</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Headphone" asp-action="Index">Headphones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Keyboard" asp-action="Index">Keyboards</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-info fw-bold" asp-area="" asp-controller="Smartwatch" asp-action="Index">Smartwatches</a>
                        </li>

                        <!-- Административна част -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-warning fw-bold" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Admin area
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item text-dark fw-bold" asp-area="Administration" asp-controller="Account" asp-action="GetUsers">Promote to admin</a></li>
                            </ul>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @if (TempData[TempDataMessage] is not null)
            {
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    @TempData[TempDataMessage]
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-danger">
        <div class="container text-center text-light fw-bold">
            &copy; @DateTime.UtcNow.Year - TechStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>