TechStore.Web/Controllers/KeyboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechStore.Core.Contracts;
using TechStore.Core.Extensions;
using TechStore.Core.Models.Keyboard;
using static TechStore.Infrastructure.Constants.DataConstant.RoleConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ProductConstants;
using static TechStore.Infrastructure.Constants.DataConstant.GlobalConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ClientConstants;
using System.Security.Claims;
using TechStore.Core.Exceptions;

namespace TechStore.Web.Controllers
{
    [Authorize]
    public class KeyboardController : Controller
    {
        private readonly IKeyboardService keyboardService;
        private readonly IClientService clientService;
        private readonly IUserService userService;

		public KeyboardController(IKeyboardService keyboardService, IClientService clientService, IUserService userService)
        {
            this.keyboardService = keyboardService;
            this.clientService = clientService;
			this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AllKeyboardsQueryModel query)
        {
            var result = await this.keyboardService.GetAllKeyboardsAsync(query.Format, query.Type, query.Wireless,
                query.Keyword, query.Sorting, query.CurrentPage);

            query.TotalProductsCount = result.TotalKeyboardsCount;

            query.Formats = await this.keyboardService.GetAllKeyboardsFormatsAsync();
            query.Types = await this.keyboardService.GetAllKeyboardsTypesAsync();

            query.Keyboards = result.Keyboards;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            try
            {
                var keyboard = await this.keyboardService.GetKeyboardByIdAsKeyboardDetailsExportViewModelAsync(id);

                if (information.ToLower() != keyboard.GetInformation().ToLower())
                {
                    return NotFound();
                }

                return View(keyboard);
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var keyboard = await this.keyboardService.GetKeyboardByIdAsKeyboardDetailsExportViewModelAsync(id);

                if (this.User.IsInRole(BestUser) && (keyboard.Seller is null || this.User.Id() != keyboard.Seller.UserId))
                {
                    return Unauthorized();
                }

                await this.keyboardService.DeleteKeyboardAsync(id);
                
                TempData[TempDataMessage] = ProductSuccessfullyDeleted;
                
                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add()
        {
	        if (this.User.IsInRole(BestUser))
	        {
				var userId = this.User.Id();

				try
				{
					var numberOfActiveSales = await this.clientService.GetNumberOfActiveSales(userId);

					if (numberOfActiveSales == MaxNumberOfAllowedSales)
					{
						ViewData["Title"] = "Add a Keyboard";

						return View(AddNotAllowedViewName);
					}
				}
				catch (TechStoreException)
				{
					return View(ErrorCommonViewName);
				}
	        }

	        return View();
		}

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add(KeyboardImportViewModel model, bool? radioButton)
        {
	        if (radioButton is null)
	        {
				this.ModelState.AddModelError("IsWireless", ErrorMessageForUnselectedOption);
			}
	        else
	        {
				model.IsWireless = radioButton;
			}

	        if (!this.ModelState.IsValid)
	        {
				return View(model);
			}

	        string? userId = null;

	        if (this.User.IsInRole(BestUser))
	        {
				userId = this.User.Id();
			}

	        try
	        {
		        int id = await this.keyboardService.AddKeyboardAsync(model, userId);

		        TempData[TempDataMessage] = ProductSuccessfullyAdded;

		        return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
			}
	        catch (TechStoreException)
	        {
		        return View(ErrorCommonViewName);
	        }
		}

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(int id)
        {
	        try
	        {
		        var keyboard = await this.keyboardService.GetKeyboardByIdAsKeyboardEditViewModelAsync(id);

		        if (this.User.IsInRole(BestUser)
		            && (keyboard.Seller is null || this.User.Id() != keyboard.Seller.UserId))
		        {
					return Unauthorized();
				}

		        return View(keyboard);
	        }
	        catch (ArgumentException)
	        {
		        return NotFound();
	        }
        }

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(KeyboardEditViewModel model)
        {
	        if (!this.ModelState.IsValid)
	        {
		        return View();
	        }

	        try
	        {
		        var keyboard = await this.keyboardService.GetKeyboardByIdAsKeyboardEditViewModelAsync(model.Id);

		        if (this.User.IsInRole(BestUser)
		            && (keyboard.Seller is null || this.User.Id() != keyboard.Seller.UserId))
		        {
					return Unauthorized();
				}

		        int id = await this.keyboardService.EditKeyboardAsync(model);

		        TempData[TempDataMessage] = ProductSuccessfullyEdited;

		        return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });

			}
	        catch (ArgumentException)
	        {
		        return NotFound();
	        }
        }

        [HttpGet]
        [Authorize(Roles = BestUser)]
        public async Task<IActionResult> Mine()
        {
	        var userId = this.User.Id();

	        try
	        {
		        var userKeyboards = await this.keyboardService.GetUserKeyboardsAsync(userId);

		        return View(userKeyboards);
			}
	        catch (TechStoreException)
	        {
		        return View(ErrorCommonViewName);
	        }
		}

        [HttpGet]
        public async Task<IActionResult> Buy(int id)
        {
	        if (this.User.IsInRole(Administrator))
	        {
		        return Unauthorized();
	        }

	        try
	        {
		        var userId = this.User.Id();

		        if (this.User.IsInRole(BestUser))
		        {
					var keyboardSeller = (await this.keyboardService.GetKeyboardByIdAsKeyboardEditViewModelAsync(id)).Seller;

					if (keyboardSeller is not null && keyboardSeller.UserId == userId)
					{
						return Unauthorized();
					}
				}

		        ViewData["Title"] = "Buy a Keyboard";

		        await this.keyboardService.MarkKeyboardAsBoughtAsync(id);

		        var client = await this.clientService.BuyProduct(userId);

		        var isNowPromotedToBestUser = await this.userService.ShouldBePromotedToBestUser(client);

		        if (isNowPromotedToBestUser)
		        {
					return View(PromoteToBestUserViewName);
				}

		        return View(PurchaseMadeViewName);
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
        }
	}
}

TechStore.Web/Views/Keyboard/Add.cshtml
@model KeyboardImportViewModel

@{
	ViewData["Title"] = "Add a Keyboard";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<div class="row">
	<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
		<form method="post">
			<div class="mb-3">
				<label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
				<input asp-for="@Model.Brand" class="form-control" aria-required="true" placeholder="Enter brand" />
				<span asp-validation-for="Brand" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.IsWireless" class="form-label">Wireless <sup>(required)</sup></label>
				<div class="form-check">
					<input type="radio" name="radioButton" value="true" />
					<label>Yes</label>
				</div>
				<div class="form-check">
					<input type="radio" name="radioButton" value="false" />
					<label>No</label>
				</div>
				<span asp-validation-for="IsWireless" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
				<input asp-for="@Model.Type" class="form-control" aria-required="true" placeholder="Gaming" />
				<span asp-validation-for="Type" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
				<input asp-for="@Model.Quantity" class="form-control" aria-required="true" placeholder="1" />
				<span asp-validation-for="Quantity" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
				<input asp-for="@Model.Price" class="form-control" aria-required="true" placeholder="50.00" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>

			@if ((this.User?.Identity?.IsAuthenticated ?? false)
					&& this.User.IsInRole(Administrator))
			{
				<div class="mb-3">
					<label asp-for="@Model.Warranty" class="form-label">Warranty (in months) <sup>(required)</sup></label>
					<input asp-for="@Model.Warranty" class="form-control" placeholder="12" />
					<span asp-validation-for="Warranty" class="text-danger"></span>
				</div>
			}

			<div class="mb-3">
				<label asp-for="@Model.Format" class="form-label">Keyboard Format</label>
				<input asp-for="@Model.Format" class="form-control" placeholder="Compact" />
				<span asp-validation-for="Format" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Color" class="form-label">Keyboard Color</label>
				<input asp-for="@Model.Color" class="form-control" placeholder="Black" />
				<span asp-validation-for="Color" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.ImageUrl" class="form-label">Keyboard Image URL <sup>(highly recommended)</sup></label>
				<input asp-for="@Model.ImageUrl" class="form-control" placeholder="https://laptop.bg/system/images/419831/double/RZ0304690100R3M1.png" />
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>

			<div class="text-center mb-3">
				<input class="btn btn-primary" type="submit" value="Add" />
			</div>
		</form>
	</div>
</div>


@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Keyboard/Details.cshtml
@model KeyboardDetailsExportViewModel
@{
	ViewData["Title"] = "Keyboard Details";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<div class="card text-center mt-5">
			@if (Model.ImageUrl is not null)
			{
				<img class="card-img-top" src="@Model.ImageUrl" alt="Keyboard Image">
			}
			<div class="card-body">
				<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
				@if (Model.IsWireless)
				{
					<p class="mb-0"><b>Wireless: <label>✔</label></b></p>
				}
				else
				{
					<p class="mb-0"><b>Wireless: <label>❌</label></b></p>
				}
				<p class="mb-0"><b>Type: @Model.Type</b></p>
				<p class="mb-0">Format: @Model.Format</p>
				<p class="mb-2">Color: @Model.Color</p>
				@if (Model.Quantity > 0)
				{
					<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>
					@if (Model.Warranty > 0)
					{
						<p class="text-success mb-2"><b>Warranty: @Model.Warranty Months</b></p>
					}
					else
					{
						<p class="text-warning mb-2"><b>This keyboard is second hand</b></p>
						<p class="text-warning mb-2"><b>Seller: @Model.SellerFirstName @Model.SellerLastName</b></p>
					}
					<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>
					@if ((this.User?.Identity?.IsAuthenticated ?? false)
										&& (!this.User.IsInRole(Administrator))
										&& ((!this.User.IsInRole(BestUser)) || (this.User.IsInRole(BestUser) && (Model.Seller is null || this.User.Id() != Model.Seller.UserId))))
					{
						<a asp-controller="Keyboard" asp-action="Buy" asp-route-id="@Model.Id" class="btn btn-success">Buy</a>
					}
				}
				else
				{
					<h5 class="text-danger mb-3">This product is out of stock!</h5>
				}
				@if ((this.User?.Identity?.IsAuthenticated ?? false)
									&& (this.User.IsInRole(Administrator) || (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId)))
				{
					<a asp-controller="Keyboard" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
					<a asp-controller="Keyboard" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
					   onclick="return confirm('Are you sure you want to delete keyboard @Model.Brand')">Delete</a>
				}
			</div>
		</div>
	</div>
</div>

TechStore.Web/Views/Keyboard/Edit.cshtml
@model KeyboardEditViewModel

@{
    ViewData["Title"] = "Edit Keyboard";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            @Html.HiddenFor(l => l.Id)
            <div class="mb-3">
                <label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
                <input asp-for="@Model.Brand" class="form-control" aria-required="true" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.IsWireless" class="form-label">Wireless <sup>(required)</sup></label>
                <select asp-for="@Model.IsWireless" class="form-control">
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                </select>
                <span asp-validation-for="IsWireless" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
                <input asp-for="@Model.Type" class="form-control" aria-required="true" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
                <input asp-for="@Model.Quantity" class="form-control" aria-required="true" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            @if ((this.User?.Identity?.IsAuthenticated ?? false)
            && this.User.IsInRole(Administrator))
            {
                <div class="mb-3">
                    <label asp-for="@Model.Warranty" class="form-label">Warranty (in months) <sup>(required)</sup></label>
                    <input asp-for="@Model.Warranty" class="form-control" />
                    <span asp-validation-for="Warranty" class="text-danger"></span>
                </div>
            }

            <div class="mb-3">
                <label asp-for="@Model.Format" class="form-label">Keyboard Format</label>
                <input asp-for="@Model.Format" class="form-control" />
                <span asp-validation-for="Format" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label">Keyboard Color</label>
                <input asp-for="@Model.Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label">Keyboard Image URL <sup>(highly recommended)</sup></label>
                <input asp-for="@Model.ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="text-center mb-3">
                <input class="btn btn-primary" type="submit" value="Save changes" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Keyboard/Index.cshtml
@model AllKeyboardsQueryModel
@{
	ViewData["Title"] = "Keyboards";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<partial name="_IndexButtonsPartial" model="@Model.Keyboards" />
<br />
<form method="get">
	<div class="row">
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Format">Keyboard format</label>
				<select asp-for="Format" class="form-control">
					<option value="">All</option>
					@foreach (var format in Model.Formats)
					{
						<option value="@format">@format</option>
					}
				</select>
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Type">Keyboard type</label>
				<select asp-for="Type" class="form-control">
					<option value="">All</option>
					@foreach (var type in Model.Types)
					{
						<option value="@type">@type</option>
					}
				</select>
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Wireless">Wireless</label>
				<select asp-for="Wireless" class="form-control">
					<option value="0">All</option>
					<option value="1">No</option>
					<option value="2">Yes</option>
				</select>
			</div>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Keyword">Search by a keyword</label>
				<input asp-for="Keyword" class="form-control" placeholder="...">
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Sorting">Sort by</label>
				<select asp-for="Sorting" class="form-control">
					<option value="0">Newest</option>
					<option value="1">Brand</option>
					<option value="2">Price(from min to max)</option>
					<option value="3">Price(from max to min)</option>
				</select>
			</div>
		</div>
	</div>
	<div class="text-center">
		<div class="form-group mt-4 p-2">
			<input type="submit" value="Search" class="btn btn-success" />
		</div>
	</div>
</form>
@if (!Model.Keyboards.Any())
{
	<h3 class="text-center mt-5">No keyboards found by the given criteria!</h3>
}
else
{
	if (Model.TotalProductsCount == 1)
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount keyboard found by the given criteria!</h4>
	}
	else
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount keyboards found by the given criteria!</h4>
	}
	<div class="row">
		<partial name="_KeyboardsIndexTablePartial" model="@Model.Keyboards" />
	</div>
	var previousPage = Model.CurrentPage - 1;
	if (previousPage < 1)
	{
		previousPage = 1;
	}
	var maxPage = Math.Ceiling((double)Model.TotalProductsCount / ProductsPerPage);
	<div class="row mt-3">
		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
			<a class="btn btn-warning @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
			   asp-controller="Keyboard"
			   asp-action="Index"
			   asp-route-currentPage="@previousPage"
			   asp-route-format="@Model.Format"
			   asp-route-type="@Model.Type"
			   asp-route-wireless="@Model.Wireless"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Prev</a>
		</div>
		@{
			var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Keyboards.Any();
		}
		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
			<a class="btn btn-warning @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
			   asp-controller="Keyboard"
			   asp-action="Index"
			   asp-route-currentPage="@(Model.CurrentPage + 1)"
			   asp-route-format="@Model.Format"
			   asp-route-type="@Model.Type"
			   asp-route-wireless="@Model.Wireless"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Next</a>
		</div>
	</div>
	<div>
		<h6 class="text-center">Page @Model.CurrentPage / @maxPage</h6>
	</div>
}

TechStore.Web/Views/Keyboard/Mine.cshtml
@model IEnumerable<KeyboardDetailsExportViewModel>

@{
	ViewData["Title"] = "My Keyboards";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

@if (Model.Any())
{
	<div class="row">

		@foreach (var keyboard in Model)
		{
			<partial name="_KeyboardPartial" model="@keyboard" />
		}
	</div>
}
else
{
	<h3 class="text-center mt-5">You have no keyboards added yet!</h3>
}

TechStore.Web/Views/Keyboard/_KeyboardPartial.cshtml
@model KeyboardDetailsExportViewModel

<div class="card col-4" style="width: 20rem;">

	@if (Model.ImageUrl is not null)
	{
		<img class="card-img-top" src="@Model.ImageUrl" alt="Keyboard image">
	}

	<div class="card-body text-center">
		<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
		@if (Model.IsWireless)
		{
			<p class="mb-0"><b>Wireless: <label>✔</label></b></p>
		}
		else
		{
			<p class="mb-0"><b>Wireless: <label>❌</label></b></p>
		}
		<p class="mb-0"><b>Type: @Model.Type</b></p>
		<p class="mb-0">Format: @Model.Format</p>
		<p class="mb-2">Color: @Model.Color</p>
		<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>
		<p class="text-success mb-2"><b>Quantity: @Model.Quantity</b></p>
		<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>

		@if ((this.User?.Identity?.IsAuthenticated ?? false)
				&& (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId))
		{
			<a asp-controller="Keyboard" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
			<a asp-controller="Keyboard" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
			   onclick="return confirm('Are you sure you want to delete keyboard @Model.Brand')">Delete</a>
		}
	</div>
</div>

TechStore.Web/Views/Keyboard/_KeyboardsIndexTablePartial.cshtml
@model IEnumerable<KeyboardExportViewModel>

<table class="table table-striped table-hover mt-5">
    <thead>
    <tr class="table-primary">
        <td>Brand</td>
        <td>Format</td>
        <td>Type</td>
        <td>Wireless</td>
        <td>Warranty</td>
        <td>Price</td>
        <td>View</td>
    </tr>
    </thead>
    <tbody>
    @foreach (var keyboard in Model)
    {
        <tr>
            <td>@keyboard.Brand</td>
            <td>@keyboard.Format</td>
            <td>@keyboard.Type</td>
            <td>
                @if (keyboard.IsWireless)
                {
                    <label>✔</label>
                }
                else
                {
                    <label>❌</label>
                }
            </td>
            <td>
                @if (keyboard.Warranty > 0)
                {
                    <p>@keyboard.Warranty months</p>
                }
                else
                {
                    <p>Second hand</p>
                }
            </td>
            <td>@String.Format("{0:f2}", keyboard.Price) EUR</td>
            <td>
                <a asp-controller="Keyboard" asp-action="Details" asp-route-id="@keyboard.Id" asp-route-information="@keyboard.GetInformation()" class="btn btn-primary">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>