TechStore.Web/Controllers/TelevisionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechStore.Core.Contracts;
using TechStore.Core.Exceptions;
using System.Security.Claims;
using TechStore.Core.Models.Television;
using static TechStore.Infrastructure.Constants.DataConstant.ClientConstants;
using static TechStore.Infrastructure.Constants.DataConstant.RoleConstants;
using static TechStore.Infrastructure.Constants.DataConstant.GlobalConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ProductConstants;
using System.Threading;
using TechStore.Core.Extensions;

namespace TechStore.Web.Controllers
{
    [Authorize]
    public class TelevisionController : Controller
    {
        private readonly ITelevisionService televisionService;
        private readonly IClientService clientService;
        private readonly IUserService userService;

		public TelevisionController(ITelevisionService televisionService, IClientService clientService, IUserService userService)
        {
            this.televisionService = televisionService;
            this.clientService = clientService;
            this.userService = userService;
        }

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] AllTelevisionsQueryModel query)
        {
            var result = await this.televisionService.GetAllTelevisionsAsync(
                query.Brand,
                query.DisplaySize,
                query.Resolution,
                query.Keyword,
                query.Sorting,
                query.CurrentPage);

            query.TotalProductsCount = result.TotalTelevisionsCount;
            query.Brands = await this.televisionService.GetAllBrandsNamesAsync();
            query.DisplaySizes = await this.televisionService.GetAllDisplaysSizesValuesAsync();
            query.Resolutions = await this.televisionService.GetAllResolutionsValuesAsync();
            query.Televisions = result.Televisions;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string information)
        {
            try
            {
                var television = await this.televisionService
                    .GetTelevisionByIdAsTelevisionDetailsExportViewModelAsync(id);

                if (information.ToLower() != television.GetInformation().ToLower())
                {
                    return NotFound();
                }

                return View(television);
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var television = await this.televisionService
                    .GetTelevisionByIdAsTelevisionDetailsExportViewModelAsync(id);

                if (this.User.IsInRole(BestUser) &&
                    (television.Seller is null || this.User.Id() != television.Seller.UserId))
                {
                    return Unauthorized();
                }

                await this.televisionService.DeleteTelevisionAsync(id);

                TempData[TempDataMessage] = ProductSuccessfullyDeleted;

                return RedirectToAction(nameof(Index));
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add()
        {
            if (this.User.IsInRole(BestUser))
            {
                var userId = this.User.Id();

                try
                {
                    var numberOfActiveSales = await this.clientService.GetNumberOfActiveSales(userId);

                    if (numberOfActiveSales == MaxNumberOfAllowedSales)
                    {
                        ViewData["Title"] = "Add a Television";

                        return View(AddNotAllowedViewName);
                    }
                }
                catch (TechStoreException)
                {
                    return View(ErrorCommonViewName);
                }
            }

            return View();
        }

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Add(TelevisionImportViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            string? userId = null;

            if (this.User.IsInRole(BestUser))
            {
                userId = this.User.Id();
            }

            try
            {
                int id = await this.televisionService.AddTelevisionAsync(model, userId);

                TempData[TempDataMessage] = ProductSuccessfullyAdded;

                return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
            }
            catch (TechStoreException)
            {
                return View(ErrorCommonViewName);
            }
        }

        [HttpGet]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var television = await this.televisionService
                    .GetTelevisionByIdAsTelevisionDetailsExportViewModelAsync(id);

                if (this.User.IsInRole(BestUser) &&
                    (television.Seller is null || this.User.Id() != television.Seller.UserId))
                {
                    return Unauthorized();
                }

                return View();
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [Authorize(Roles = $"{Administrator}, {BestUser}")]
        public async Task<IActionResult> Edit(TelevisionEditViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                var television = await this.televisionService
                    .GetTelevisionByIdAsTelevisionDetailsExportViewModelAsync(model.Id);

                if (this.User.IsInRole(BestUser) &&
                    (television.Seller is null || this.User.Id() != television.Seller.UserId))
                {
                    return Unauthorized();
                }

                int id = await this.televisionService.EditTelevisionAsync(model);

                TempData[TempDataMessage] = ProductSuccessfullyEdited;

                return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
            }
            catch (ArgumentException)
            {
                return NotFound();
            }
        }

        [HttpGet]
        [Authorize(Roles = BestUser)]
        public async Task<IActionResult> Mine()
        {
	        var userId = this.User.Id();

	        try
	        {
		        var userTelevisions = await this.televisionService.GetUserTelevisionsAsync(userId);

		        return View(userTelevisions);
			}
	        catch (TechStoreException)
	        {
		        return View(ErrorCommonViewName);
	        }
		}

        [HttpGet]
        public async Task<IActionResult> Buy(int id)
        {
	        if (this.User.IsInRole(Administrator))
	        {
		        return Unauthorized();
	        }

	        try
	        {
		        var userId = this.User.Id();

		        if (this.User.IsInRole(BestUser))
		        {
					var televisionSeller = (await this.televisionService.GetTelevisionByIdAsTelevisionDetailsExportViewModelAsync(id)).Seller;

					if (televisionSeller is not null && televisionSeller.UserId == userId)
					{
						return Unauthorized();
					}
				}

		        ViewData["Title"] = "Buy a Television";
		        await this.televisionService.MarkTelevisionAsBoughtAsync(id);
		        var client = await this.clientService.BuyProduct(userId);
		        var isNowPromotedToBestUser = await this.userService.ShouldBePromotedToBestUser(client);

		        if (isNowPromotedToBestUser)
		        {
					return View(PromoteToBestUserViewName);
				}

		        return View(PurchaseMadeViewName);

			}
	        catch (ArgumentException)
	        {
				return NotFound();
			}
        }
	}
}

TechStore.Web/Views/Television/Add.cshtml
@model TelevisionImportViewModel
@{
    ViewData["Title"] = "Add a Television";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            <div class="mb-3">
                <label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
                <input asp-for="@Model.Brand" class="form-control" aria-required="true" placeholder="Enter brand" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.DisplaySize" class="form-label">Display Size (in inches) <sup>(required)</sup></label>
                <input asp-for="@Model.DisplaySize" class="form-control" aria-required="true" placeholder="24.5" />
                <span asp-validation-for="DisplaySize" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Resolution" class="form-label">Display Resolution <sup>(required)</sup></label>
                <input asp-for="@Model.Resolution" class="form-control" placeholder="3840x2160 4K Ultra HD" />
                <span asp-validation-for="Resolution" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
                <input asp-for="@Model.Type" class="form-control" aria-required="true" placeholder="For graphic design" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
                <input asp-for="@Model.Quantity" class="form-control" aria-required="true" placeholder="1" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" placeholder="1250.00" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @if ((this.User?.Identity?.IsAuthenticated ?? false)
            && this.User.IsInRole(Administrator))
            {
                <div class="mb-3">
                    <label asp-for="@Model.Warranty" class="form-label">Warranty (in months) <sup>(required)</sup></label>
                    <input asp-for="@Model.Warranty" class="form-control" placeholder="12" />
                    <span asp-validation-for="Warranty" class="text-danger"></span>
                </div>
            }
            <div class="mb-3">
                <label asp-for="@Model.DisplayTechnology" class="form-label">Display Technology</label>
                <input asp-for="@Model.DisplayTechnology" class="form-control" placeholder="LED" />
                <span asp-validation-for="DisplayTechnology" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label">Television Color</label>
                <input asp-for="@Model.Color" class="form-control" placeholder="Black" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label">Television Image URL <sup>(highly recommended)</sup></label>
                <input asp-for="@Model.ImageUrl" class="form-control" placeholder="https://cdncloudcart.com/402/products/images/159038/televizor-samsung-qe43q67dauxxh--108-sm-3840x2160-uhd-4k--43-inch-qled-67336d615352e_800x800.jpeg?1731423609" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <input class="btn btn-primary" type="submit" value="Add" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Television/Details.cshtml
@model TelevisionDetailsExportViewModel
@{
	ViewData["Title"] = "Television Details";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<div class="row">
	<div class="col-sm-2"></div>
	<div class="col-sm-8">
		<div class="card text-center mt-5">
			@if (Model.ImageUrl is not null)
			{
				<img class="card-img-top" src="@Model.ImageUrl" alt="Television Image">
			}
			<div class="card-body">
				<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
				<p class="mb-0"><b>Display Size: @Model.DisplaySize inches</b></p>
				<p class="mb-0"><b>Display Resolution: @Model.Resolution</b></p>
				<p class="mb-0"><b>Display Technology: @Model.DisplayTechnology</b></p>
				<p class="mb-0">Type: @Model.Type</p>
				<p class="mb-2">Color: @Model.Color</p>
				@if (Model.Quantity > 0)
				{
					<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>
					@if (Model.Warranty > 0)
					{
						<p class="text-success mb-2"><b>Warranty: @Model.Warranty months</b></p>
					}
					else
					{
						<p class="text-warning mb-2"><b>This Television is second hand</b></p>
						<p class="text-warning mb-2"><b>Seller: @Model.SellerFirstName @Model.SellerLastName</b></p>
					}
					<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>
					@if ((this.User?.Identity?.IsAuthenticated ?? false)
										&& (!this.User.IsInRole(Administrator))
										&& ((!this.User.IsInRole(BestUser)) || (this.User.IsInRole(BestUser) && (Model.Seller is null || this.User.Id() != Model.Seller.UserId))))
					{
						<a asp-controller="Television" asp-action="Buy" asp-route-id="@Model.Id" class="btn btn-success">Buy</a>
					}
				}
				else
				{
					<h5 class="text-danger mb-3">This product is out of stock!</h5>
				}
				@if ((this.User?.Identity?.IsAuthenticated ?? false)
									&& (this.User.IsInRole(Administrator) || (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId)))
				{
					<a asp-controller="Television" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
					<a asp-controller="Television" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
					   onclick="return confirm('Are you sure you want to delete television @Model.Brand')">Delete</a>
				}
			</div>
		</div>
	</div>
</div>

TechStore.Web/Views/Television/Edit.cshtml
@model TelevisionEditViewModel
@{
    ViewData["Title"] = "Edit Television";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            @Html.HiddenFor(l => l.Id)
            <div class="mb-3">
                <label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
                <input asp-for="@Model.Brand" class="form-control" aria-required="true" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.DisplaySize" class="form-label">Display Size (in inches) <sup>(required)</sup></label>
                <input asp-for="@Model.DisplaySize" class="form-control" aria-required="true" />
                <span asp-validation-for="DisplaySize" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Resolution" class="form-label">Display Resolution <sup>(required)</sup></label>
                <input asp-for="@Model.Resolution" class="form-control" />
                <span asp-validation-for="Resolution" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
                <input asp-for="@Model.Type" class="form-control" aria-required="true" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
                <input asp-for="@Model.Quantity" class="form-control" aria-required="true" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            @if ((this.User?.Identity?.IsAuthenticated ?? false)
            && this.User.IsInRole(Administrator))
            {
                <div class="mb-3">
                    <label asp-for="@Model.Warranty" class="form-label">Warranty (In Months) <sup>(required)</sup></label>
                    <input asp-for="@Model.Warranty" class="form-control" />
                    <span asp-validation-for="Warranty" class="text-danger"></span>
                </div>
            }
            <div class="mb-3">
                <label asp-for="@Model.DisplayTechnology" class="form-label">Display Technology</label>
                <input asp-for="@Model.DisplayTechnology" class="form-control" />
                <span asp-validation-for="DisplayTechnology" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label">Television Color</label>
                <input asp-for="@Model.Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label">Television Image URL <sup>(highly recommended)</sup></label>
                <input asp-for="@Model.ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="text-center mb-3">
                <input class="btn btn-primary" type="submit" value="Save Changes" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Television/Index.cshtml
@model TechStore.Core.Models.Television.AllTelevisionsQueryModel
@{
	ViewData["Title"] = "Televisions";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
<partial name="_IndexButtonsPartial" model="@Model.Televisions" />
<br />
<form method="get">
	<div class="row">
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Brand">Brand</label>
				<select asp-for="Brand" class="form-control">
					<option value="">All</option>
					@foreach (var brand in Model.Brands)
					{
						<option value="@brand">@brand</option>
					}
				</select>
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="DisplaySize">Display Size (in inches)</label>
				<select asp-for="DisplaySize" class="form-control">
					<option value="">All</option>
					@foreach (var displaySize in Model.DisplaySizes)
					{
						<option value="@displaySize">@displaySize</option>
					}
				</select>
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Resolution">Resolution</label>
				<select asp-for="Resolution" class="form-control">
					<option value="">All</option>
					@foreach (var resolution in Model.Resolutions)
					{
						<option value="@resolution">@resolution</option>
					}
				</select>
			</div>
		</div>
	</div>
	<br />
	<div class="row">
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Keyword">Search by a keyword</label>
				<input asp-for="Keyword" class="form-control" placeholder="...">
			</div>
		</div>
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Sorting">Sort by</label>
				<select asp-for="Sorting" class="form-control">
					<option value="0">Newest</option>
					<option value="1">Brand</option>
					<option value="2">Price(From Min To Max)</option>
					<option value="3">Price(From Max To Min)</option>
				</select>
			</div>
		</div>
	</div>
	<div class="text-center">
		<div class="form-group mt-4 p-2">
			<input type="submit" value="Search" class="btn btn-success" />
		</div>
	</div>
</form>
@if (!Model.Televisions.Any())
{
	<h3 class="text-center mt-5">No Televisions found by the given criteria!</h3>
}
else
{
	if (Model.TotalProductsCount == 1)
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount Television found by the given criteria!</h4>
	}
	else
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount Televisions found by the given criteria!</h4>
	}
	<div class="row">
		<partial name="_TelevisionsIndexTablePartial" model="@Model.Televisions" />
	</div>
	var previousPage = Model.CurrentPage - 1;
	if (previousPage < 1)
	{
		previousPage = 1;
	}
	var maxPage = Math.Ceiling((double)Model.TotalProductsCount / ProductsPerPage);
	<div class="row mt-3">
		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
			<a class="btn btn-warning @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
			   asp-controller="Television"
			   asp-action="Index"
			   asp-route-currentPage="@previousPage"
			   asp-route-brand="@Model.Brand"
			   asp-route-displaySize="@Model.DisplaySize"
			   asp-route-resolution="@Model.Resolution"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Prev</a>
		</div>
		@{
			var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Televisions.Any();
		}
		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
			<a class="btn btn-warning @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
			   asp-controller="Television"
			   asp-action="Index"
			   asp-route-currentPage="@(Model.CurrentPage + 1)"
			   asp-route-brand="@Model.Brand"
			   asp-route-displaySize="@Model.DisplaySize"
			   asp-route-resolution="@Model.Resolution"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Next</a>
		</div>
	</div>
	<div>
		<h6 class="text-center">Page @Model.CurrentPage / @maxPage</h6>
	</div>
}

TechStore.Web/Views/Television/Mine.cshtml
@model IEnumerable<TelevisionDetailsExportViewModel>
@{
	ViewData["Title"] = "My Televisions";
}
<h1 class="text-center mb-2">@ViewData["Title"]</h1>
<hr />
@if (Model.Any())
{
		<div class="row">
		@foreach (var television in Model)
		{
					<partial name="_TelevisionPartial" model="@television" />
		}
		</div>
}
else
{
		<h3 class="text-center mt-5">You have no televisions added yet!</h3>
}

TechStore.Web/Views/Television/_TelevisionPartial.cshtml
@model TelevisionDetailsExportViewModel

<div class="card col-4" style="width: 20rem;">
	@if (Model.ImageUrl is not null)
	{
		<img class="card-img-top" src="@Model.ImageUrl" alt="Television image">
	}
	<div class="card-body text-center">
		<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
		<p class="mb-0">Display Size: @Model.DisplaySize inches</p>
		<p class="mb-0">Resolution: @Model.Resolution</p>
		<p class="mb-0">Display Technology: @Model.DisplayTechnology</p>
		<p class="mb-0">Display Coverage: @Model.DisplayCoverage</p>
		<p class="mb-0">Type: @Model.Type</p>
		<p class="mb-2">Color: @Model.Color</p>
		<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>
		<p class="text-success mb-2"><b>Quantity: @Model.Quantity</b></p>
		<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>
		@if ((this.User?.Identity?.IsAuthenticated ?? false)
				&& (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId))
		{
			<a asp-controller="Television" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
			<a asp-controller="Television" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
			   onclick="return confirm('Are you sure you want to delete television @Model.Brand')">Delete</a>
		}
	</div>
</div>

TechStore.Web/Views/Television/_TelevisionsIndexTablePartial.cshtml
@model IEnumerable<TelevisionExportViewModel>

<table class="table table-striped table-hover mt-5">
	<thead>
		<tr class="table-primary">
			<td>Brand</td>
			<td>Display Size</td>
			<td>Display Resolution</td>
			<td>Display Technology</td>
			<td>Display Coverage</td>
			<td>Warranty</td>
			<td>Price</td>
			<td>View</td>
		</tr>
	</thead>
	<tbody>
		@foreach (var television in Model)
		{
			<tr>
				<td>@television.Brand</td>
				<td>@television.DisplaySize inches</td>
				<td>@television.Resolution</td>
				<td>@television.DisplayTechnology</td>
				<td>@television.DisplayCoverage</td>
				<td>
					@if (television.Warranty > 0)
					{
						<p>@television.Warranty Months</p>
					}
					else
					{
						<p>Second hand</p>
					}
				</td>
				<td>@String.Format("{0:f2}", television.Price) EUR</td>
				<td>
                    <a asp-controller="Television" asp-action="Details" asp-route-id="@television.Id" asp-route-information="@television.GetInformation()" class="btn btn-primary">Details</a>
				</td>
			</tr>
		}
	</tbody>
</table>