TechStore.Web/Controllers/HeadphoneController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechStore.Core.Contracts;
using TechStore.Core.Exceptions;
using TechStore.Core.Extensions;
using TechStore.Core.Models.Headphone;
using static TechStore.Infrastructure.Constants.DataConstant.RoleConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ProductConstants;
using static TechStore.Infrastructure.Constants.DataConstant.GlobalConstants;
using static TechStore.Infrastructure.Constants.DataConstant.ClientConstants;

namespace TechStore.Web.Controllers
{
	[Authorize]
	public class HeadphoneController : Controller
	{
		private readonly IHeadphoneService headphoneService;
		private readonly IClientService clientService;
		private readonly IUserService userService;

		public HeadphoneController(IHeadphoneService headphoneService, IClientService clientService, IUserService userService)
		{
			this.headphoneService = headphoneService;
			this.clientService = clientService;
			this.userService = userService;
		}

		[HttpGet]
		public async Task<IActionResult> Index([FromQuery] AllHeadphonesQueryModel query)
		{
			var result = await this.headphoneService.GetAllHeadphonesAsync(
				query.Type,
				query.Wireless,
				query.Keyword,
				query.Sorting,
				query.CurrentPage);

			query.TotalProductsCount = result.TotalHeadphonesCount;
			query.Types = await this.headphoneService.GetAllHeadphonesTypesAsync();
			query.Headphones = result.Headphones;

			return View(query);
		}

		[HttpGet]
		public async Task<IActionResult> Details(int id, string information)
		{
			try
			{
				var headphone = await this.headphoneService.GetHeadphoneByIdAsHeadphoneDetailsExportViewModelAsync(id);

				if (information.ToLower() != headphone.GetInformation().ToLower())
				{
					return NotFound();
				}

				return View(headphone);
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Delete(int id)
		{
			try
			{
				var headphone = await this.headphoneService.GetHeadphoneByIdAsHeadphoneDetailsExportViewModelAsync(id);

				if (this.User.IsInRole(BestUser)
					&& (headphone.Seller is null || this.User.Id() != headphone.Seller.UserId))
				{
					return Unauthorized();
				}

				await this.headphoneService.DeleteHeadphoneAsync(id);

				TempData[TempDataMessage] = ProductSuccessfullyDeleted;

				return RedirectToAction(nameof(Index));
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Add()
		{
			if (this.User.IsInRole(BestUser))
			{
				var userId = this.User.Id();

				try
				{
					var numberOfActiveSales = await this.clientService.GetNumberOfActiveSales(userId);

					if (numberOfActiveSales == MaxNumberOfAllowedSales)
					{
						ViewData["Title"] = "Add a Headphone";

						return View(AddNotAllowedViewName);
					}
				}
				catch (TechStoreException)
				{
					return View(ErrorCommonViewName);
				}

				var model = new HeadphoneImportViewModel();

				return View(model);
			}

			return Unauthorized();
		}

		[HttpPost]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Add(HeadphoneImportViewModel model, bool? rbIsWireless, bool? rbHasMicrophone)
		{
			if (rbIsWireless is null && rbHasMicrophone is null)
			{
				this.ModelState.AddModelError("IsWireless", ErrorMessageForUnselectedOption);
				this.ModelState.AddModelError("HasMicrophone", ErrorMessageForUnselectedOption);
			}
			else if (rbIsWireless is null)
			{
				this.ModelState.AddModelError("IsWireless", ErrorMessageForUnselectedOption);
				model.HasMicrophone = rbHasMicrophone;
			}
			else if (rbHasMicrophone is null)
			{
				this.ModelState.AddModelError("HasMicrophone", ErrorMessageForUnselectedOption);
				model.IsWireless = rbIsWireless;
			}
			else
			{
				model.IsWireless = rbIsWireless;
				model.HasMicrophone = rbHasMicrophone;
			}

			if (!this.ModelState.IsValid)
			{
				return View(model);
			}

			string? userId = null;

			if (this.User.IsInRole(BestUser))
			{
				userId = this.User.Id();
			}

			try
			{
				int id = await this.headphoneService.AddHeadphoneAsync(model, userId);

				TempData[TempDataMessage] = ProductSuccessfullyAdded;

				return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });
			}
			catch (TechStoreException)
			{
				return View(ErrorCommonViewName);
			}
			catch (ArgumentException)
			{
				return View(ErrorCommonViewName);
			}
		}

		[HttpGet]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Edit(int id)
		{
			try
			{
				var headphone = await this.headphoneService.GetHeadphoneByIdAsHeadphoneEditViewModelAsync(id);

				if (this.User.IsInRole(BestUser)
				    && (headphone.Seller is null || this.User.Id() != headphone.Seller.UserId))
				{
					return Unauthorized();
				}

				return View(headphone);

			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpPost]
		[Authorize(Roles = $"{Administrator}, {BestUser}")]
		public async Task<IActionResult> Edit(HeadphoneEditViewModel model)
		{
			if (!this.ModelState.IsValid)
			{
				return View(model);
			}

			try
			{
				var headphone = await this.headphoneService.GetHeadphoneByIdAsHeadphoneEditViewModelAsync(model.Id);

				if (this.User.IsInRole(BestUser)
				    && (headphone.Seller is null || this.User.Id() != headphone.Seller.UserId))
				{
					return Unauthorized();
				}

				int id = await this.headphoneService.EditHeadphoneAsync(model);

				TempData[TempDataMessage] = ProductSuccessfullyEdited;

				return RedirectToAction(nameof(Details), new { id, information = model.GetInformation() });

			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}

		[HttpGet]
		[Authorize(Roles = BestUser)]
		public async Task<IActionResult> Mine()
		{
			var userId = this.User.Id();

			try
			{
				var userHeadphones = await this.headphoneService.GetUserHeadphonesAsync(userId);

				return View(userHeadphones);
			}
			catch (TechStoreException)
			{
				return View(ErrorCommonViewName);
			}
		}

		[HttpGet]
		public async Task<IActionResult> Buy(int id)
		{
			if (this.User.IsInRole(Administrator))
			{
				return Unauthorized();
			}

			try
			{
				var userId = this.User.Id();

				if (this.User.IsInRole(BestUser))
				{
					var headphoneSeller = (await this.headphoneService.GetHeadphoneByIdAsHeadphoneEditViewModelAsync(id)).Seller;

					if (headphoneSeller is not null && headphoneSeller.UserId == userId)
					{
						return Unauthorized();
					}
				}

				ViewData["Title"] = "Buy a Headphone";

				await this.headphoneService.MarkHeadphoneAsBoughtAsync(id);

				var client = await this.clientService.BuyProduct(userId);

				var isNowPromotedToBestUser = await this.userService.ShouldBePromotedToBestUser(client);

				if (isNowPromotedToBestUser)
				{
					return View(PromoteToBestUserViewName);
				}

				return View(PurchaseMadeViewName);
			}
			catch (ArgumentException)
			{
				return NotFound();
			}
		}
	}
}

TechStore.Web/Views/Headphone/Add.cshtml
@model HeadphoneImportViewModel

@{
	ViewData["Title"] = "Add a Headphone";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<div class="row">
	<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
		<form method="post">
			<div class="mb-3">
				<label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
				<input asp-for="@Model.Brand" class="form-control" aria-required="true" placeholder="Enter brand" />
				<span asp-validation-for="Brand" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
				<input asp-for="@Model.Type" class="form-control" aria-required="true" placeholder="Over-ear" />
				<span asp-validation-for="Type" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.IsWireless" class="form-label">Wireless <sup>(required)</sup></label>
				<div class="form-check">
					@if (Model.IsWireless == true)
					{
						<input type="radio" name="rbIsWireless" value="true" checked />
					}
					else
					{
						<input type="radio" name="rbIsWireless" value="true" />
					}
					<label>Yes</label>
				</div>
				<div class="form-check">
					@if (Model.IsWireless == false)
					{
						<input type="radio" name="rbIsWireless" value="false" checked />
					}
					else
					{
						<input type="radio" name="rbIsWireless" value="false" />
					}
					<label>No</label>
				</div>
				<span asp-validation-for="IsWireless" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.HasMicrophone" class="form-label">Microphone <sup>(required)</sup></label>
				<div class="form-check">
					@if (Model.HasMicrophone == true)
					{
						<input type="radio" name="rbHasMicrophone" value="true" checked />
					}
					else
					{
						<input type="radio" name="rbHasMicrophone" value="true" />
					}
					<label>Yes</label>
				</div>
				<div class="form-check">
					@if (Model.HasMicrophone == false)
					{
						<input type="radio" name="rbHasMicrophone" value="false" checked />
					}
					else
					{
						<input type="radio" name="rbHasMicrophone" value="false" />
					}
					<label>No</label>
				</div>
				<span asp-validation-for="HasMicrophone" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
				<input asp-for="@Model.Quantity" class="form-control" aria-required="true" placeholder="1" />
				<span asp-validation-for="Quantity" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
				<input asp-for="@Model.Price" class="form-control" aria-required="true" placeholder="50.00" />
				<span asp-validation-for="Price" class="text-danger"></span>
			</div>

			@if ((this.User?.Identity?.IsAuthenticated ?? false)
					&& this.User.IsInRole(Administrator))
			{
				<div class="mb-3">
					<label asp-for="@Model.Warranty" class="form-label">Warranty (in months) <sup>(required)</sup></label>
					<input asp-for="@Model.Warranty" class="form-control" />
					<span asp-validation-for="Warranty" class="text-danger"></span>
				</div>
			}

			<div class="mb-3">
				<label asp-for="@Model.Color" class="form-label">Headphone Color</label>
				<input asp-for="@Model.Color" class="form-control" placeholder="Black" />
				<span asp-validation-for="Color" class="text-danger"></span>
			</div>
			<div class="mb-3">
				<label asp-for="@Model.ImageUrl" class="form-label">Headphone Image URL <sup>(highly recommended)</sup></label>
				<input asp-for="@Model.ImageUrl" class="form-control" placeholder="https://laptop.bg/system/images/296698/double/lenovo_ideapad_3_15_ultraslim_gen_6_82KU004NBM.png" />
				<span asp-validation-for="ImageUrl" class="text-danger"></span>
			</div>

			<div class="text-center mb-3">
				<input class="btn btn-primary" type="submit" value="Add" />
			</div>
		</form>
	</div>
</div>


@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Headphone/Details.cshtml
@model HeadphoneDetailsExportViewModel

@{
	ViewData["Title"] = "Headphone Details";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<div class="row">

	<div class="col-sm-2"></div>

	<div class="col-sm-8">

		<div class="card text-center mt-5">

			@if (Model.ImageUrl is not null)
			{
				<img class="card-img-top" src="@Model.ImageUrl" alt="Headphone image">
			}

			<div class="card-body">
				<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
				@if (Model.IsWireless)
				{
					<p class="mb-0"><b>Wireless: <label>✔</label></b></p>
				}
				else
				{
					<p class="mb-0"><b>Wireless: <label>❌</label></b></p>
				}
				@if (Model.HasMicrophone)
				{
					<p class="mb-0"><b>Microphone: <label>✔</label></b></p>
				}
				else
				{
					<p class="mb-0"><b>Microphone: <label>❌</label></b></p>
				}
				<p class="mb-0"><b>Type: @Model.Type</b></p>
				<p class="mb-2">Color: @Model.Color</p>

				@if (Model.Quantity > 0)
				{
					<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>

					@if (Model.Warranty > 0)
					{
						<p class="text-success mb-2"><b>Warranty: @Model.Warranty months</b></p>
					}
					else
					{
						<p class="text-warning mb-2"><b>This headphone is second hand</b></p>
						<p class="text-warning mb-2"><b>Seller: @Model.SellerFirstName @Model.SellerLastName</b></p>
					}

					<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>

					@if ((this.User?.Identity?.IsAuthenticated ?? false)
										&& (!this.User.IsInRole(Administrator))
										&& ((!this.User.IsInRole(BestUser)) || (this.User.IsInRole(BestUser) && (Model.Seller is null || this.User.Id() != Model.Seller.UserId))))
					{
						<a asp-controller="Headphone" asp-action="Buy" asp-route-id="@Model.Id" class="btn btn-success">Buy</a>
					}
				}
				else
				{
					<h5 class="text-danger mb-3">This product is out of stock!</h5>
				}

				@if ((this.User?.Identity?.IsAuthenticated ?? false)
									&& (this.User.IsInRole(Administrator) || (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId)))
				{
					<a asp-controller="Headphone" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
					<a asp-controller="Headphone" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
					   onclick="return confirm('Are you sure you want to delete headphone @Model.Brand')">Delete</a>
				}

			</div>

		</div>

	</div>

</div>

TechStore.Web/Views/Headphone/Edit.cshtml
@model HeadphoneEditViewModel

@{
    ViewData["Title"] = "Edit Headphone";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<div class="row">
    <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
        <form method="post">
            @Html.HiddenFor(l => l.Id)
            <div class="mb-3">
                <label asp-for="@Model.Brand" class="form-label">Brand <sup>(required)</sup></label>
                <input asp-for="@Model.Brand" class="form-control" aria-required="true" />
                <span asp-validation-for="Brand" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.IsWireless" class="form-label">Wireless <sup>(required)</sup></label>
                <select asp-for="@Model.IsWireless" class="form-control">
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                </select>
                <span asp-validation-for="IsWireless" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.HasMicrophone" class="form-label">Microphone <sup>(required)</sup></label>
                <select asp-for="@Model.HasMicrophone" class="form-control">
                    <option value="true">Yes</option>
                    <option value="false">No</option>
                </select>
                <span asp-validation-for="HasMicrophone" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Type" class="form-label">Type <sup>(required)</sup></label>
                <input asp-for="@Model.Type" class="form-control" aria-required="true" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Quantity" class="form-label">Quantity <sup>(required)</sup></label>
                <input asp-for="@Model.Quantity" class="form-control" aria-required="true" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.Price" class="form-label">Price <sup>(required)</sup></label>
                <input asp-for="@Model.Price" class="form-control" aria-required="true" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            @if ((this.User?.Identity?.IsAuthenticated ?? false)
            && this.User.IsInRole(Administrator))
            {
                <div class="mb-3">
                    <label asp-for="@Model.Warranty" class="form-label">Warranty (in months) <sup>(required)</sup></label>
                    <input asp-for="@Model.Warranty" class="form-control" />
                    <span asp-validation-for="Warranty" class="text-danger"></span>
                </div>
            }

            <div class="mb-3">
                <label asp-for="@Model.Color" class="form-label">Headphone Color</label>
                <input asp-for="@Model.Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label asp-for="@Model.ImageUrl" class="form-label">Headphone Image URL <sup>(highly recommended)</sup></label>
                <input asp-for="@Model.ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>

            <div class="text-center mb-3">
                <input class="btn btn-primary" type="submit" value="Save changes" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TechStore.Web/Views/Headphone/Index.cshtml
@model AllHeadphonesQueryModel

@{
	ViewData["Title"] = "Headphones";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

<partial name="_IndexButtonsPartial" model="@Model.Headphones" />

<br />

<form method="get">
	<div class="row">
		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Type">Headphone type</label>
				<select asp-for="Type" class="form-control">
					<option value="">All</option>
					@foreach (var type in Model.Types)
					{
						<option value="@type">@type</option>
					}
				</select>
			</div>
		</div>

		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Wireless">Wireless</label>
				<select asp-for="Wireless" class="form-control">
					<option value="0">All</option>
					<option value="1">No</option>
					<option value="2">Yes</option>
				</select>
			</div>
		</div>

		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Keyword">Search by a keyword</label>
				<input asp-for="Keyword" class="form-control" placeholder="...">
			</div>
		</div>

		<div class="form-group col-md-3">
			<div class="form-group">
				<label asp-for="Sorting">Sort by</label>
				<select asp-for="Sorting" class="form-control">
					<option value="0">Newest</option>
					<option value="1">Brand</option>
					<option value="2">Price(From Min To Max)</option>
					<option value="3">Price(From Max To Min)</option>
				</select>
			</div>
		</div>
	</div>

	<div class="text-center">
		<div class="form-group mt-4 p-2">
			<input type="submit" value="Search" class="btn btn-success" />
		</div>
	</div>
</form>

@if (!Model.Headphones.Any())
{
	<h3 class="text-center mt-5">No headphones found by the given criteria!</h3>
}
else
{
	if (Model.TotalProductsCount == 1)
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount headphone found by the given criteria!</h4>
	}
	else
	{
		<h4 class="text-center mt-4">@Model.TotalProductsCount headphones found by the given criteria!</h4>
	}

	<div class="row">
		<partial name="_HeadphonesIndexTablePartial" model="@Model.Headphones" />
	</div>

	var previousPage = Model.CurrentPage - 1;

	if (previousPage < 1)
	{
		previousPage = 1;
	}

	var maxPage = Math.Ceiling((double)Model.TotalProductsCount / ProductsPerPage);

	<div class="row mt-3">
		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
			<a class="btn btn-warning @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
			   asp-controller="Headphone"
			   asp-action="Index"
			   asp-route-currentPage="@previousPage"
			   asp-route-type="@Model.Type"
			   asp-route-wireless="@Model.Wireless"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Prev</a>
		</div>

		@{
			var shouldButtonBeDisabled = Model.CurrentPage == maxPage || !Model.Headphones.Any();
		}

		<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
			<a class="btn btn-warning @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
			   asp-controller="Headphone"
			   asp-action="Index"
			   asp-route-currentPage="@(Model.CurrentPage + 1)"
			   asp-route-type="@Model.Type"
			   asp-route-wireless="@Model.Wireless"
			   asp-route-keyWord="@Model.Keyword"
			   asp-route-sorting="@((int)Model.Sorting)">Next</a>
		</div>
	</div>

	<div>
		<h6 class="text-center">Page @Model.CurrentPage / @maxPage</h6>
	</div>
}

TechStore.Web/Views/Headphone/Mine.cshtml
@model IEnumerable<HeadphoneDetailsExportViewModel>

@{
	ViewData["Title"] = "My Headphones";
}

<h1 class="text-center mb-2">@ViewData["Title"]</h1>

<hr />

@if (Model.Any())
{
	<div class="row">

		@foreach (var headphone in Model)
		{
			<partial name="_HeadphonePartial" model="@headphone" />
		}
	</div>
}
else
{
	<h3 class="text-center mt-5">You have no headphones added yet!</h3>
}

TechStore.Web/Views/Headphone/_HeadphonePartial.cshtml
@model HeadphoneDetailsExportViewModel

<div class="card col-4" style="width: 20rem;">

	@if (Model.ImageUrl is not null)
	{
		<img class="card-img-top" src="@Model.ImageUrl" alt="Headphone image">
	}

	<div class="card-body text-center">
		<h4 class="card-title mt-2 mb-3">@Model.Brand</h4>
		@if (Model.IsWireless)
		{
			<p class="mb-0"><b>Wireless: <label>✔</label></b></p>
		}
		else
		{
			<p class="mb-0"><b>Wireless: <label>❌</label></b></p>
		}
		@if (Model.HasMicrophone)
		{
			<p class="mb-0"><b>Microphone: <label>✔</label></b></p>
		}
		else
		{
			<p class="mb-0"><b>Microphone: <label>❌</label></b></p>
		}
		<p class="mb-0"><b>Type: @Model.Type</b></p>
		<p class="mb-2">Color: @Model.Color</p>
		<p class="text-success mb-2"><b>On sale from: @Model.AddedOn</b></p>
		<p class="text-success mb-2"><b>Quantity: @Model.Quantity</b></p>
		<p class="text-success mb-3"><b>Price: @String.Format("{0:f2}", Model.Price) EUR</b></p>

		@if ((this.User?.Identity?.IsAuthenticated ?? false)
				&& (this.User.IsInRole(BestUser) && Model.Seller is not null && this.User.Id() == Model.Seller.UserId))
		{
			<a asp-controller="Headphone" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
			<a asp-controller="Headphone" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"
			   onclick="return confirm('Are you sure you want to delete headphone @Model.Brand')">Delete</a>
		}
	</div>
</div>

TechStore.Web/Views/Headphone/_HeadphonesIndexTablePartial.cshtml
@model IEnumerable<HeadphoneExportViewModel>

<table class="table table-striped table-hover mt-5">
	<thead>
		<tr class="table-primary">
			<td>Brand</td>
			<td>Type</td>
			<td>Wireless</td>
			<td>Microphone</td>
			<td>Warranty</td>
			<td>Price</td>
			<td>View</td>
		</tr>
	</thead>
	<tbody>
		@foreach (var headphone in Model)
		{
			<tr>
				<td>@headphone.Brand</td>
				<td>@headphone.Type</td>
				<td>
					@if (headphone.IsWireless)
					{
						<label>✔</label>
					}
					else
					{
						<label>❌</label>
					}
				</td>
				<td>
					@if (headphone.HasMicrophone)
					{
						<label>✔</label>
					}
					else
					{
						<label>❌</label>
					}
				</td>
				<td>
					@if (headphone.Warranty > 0)
					{
						<p>@headphone.Warranty months</p>
					}
					else
					{
						<p>Second hand</p>
					}
				</td>
				<td>@String.Format("{0:f2}", headphone.Price) EUR</td>
				<td>
					<a asp-controller="Headphone" asp-action="Details" asp-route-id="@headphone.Id" asp-route-information="@headphone.GetInformation()" class="btn btn-primary">Details</a>
				</td>
			</tr>
		}
	</tbody>
</table>